"use client"

import { useState, useEffect } from "react"
import { collection, query, orderBy, getDocs } from "firebase/firestore"
import { db } from "../lib/firebase"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { toast } from "@/components/ui/use-toast"

interface ZReport {
  id: string
  date: Date
  totalSales: number
  generatedBy: string
}

export function AdminZReports() {
  const [zReports, setZReports] = useState<ZReport[]>([])
  const [totalStoreSales, setTotalStoreSales] = useState(0)

  useEffect(() => {
    fetchZReports()
  }, [])

  const fetchZReports = async () => {
    try {
      const zReportsRef = collection(db, "zreports")
      const q = query(zReportsRef, orderBy("date", "desc"))
      const querySnapshot = await getDocs(q)

      const reports: ZReport[] = []
      let total = 0

      querySnapshot.forEach((doc) => {
        const data = doc.data()
        reports.push({
          id: doc.id,
          date: data.date.toDate(),
          totalSales: data.totalSales,
          generatedBy: data.generatedBy,
        })
        total += data.totalSales
      })

      setZReports(reports)
      setTotalStoreSales(total)
    } catch (error) {
      console.error("Error fetching Z-reports:", error)
      toast({
        title: "Error",
        description: "Failed to fetch Z-reports. Please try again.",
        variant: "destructive",
      })
    }
  }

  return (
    <div>
      <h2 className="text-xl font-semibold mb-4">Z-Reports</h2>
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>Date</TableHead>
            <TableHead>Total Sales</TableHead>
            <TableHead>Generated By</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {zReports.map((report) => (
            <TableRow key={report.id}>
              <TableCell>{report.date.toLocaleDateString()}</TableCell>
              <TableCell>ETB {report.totalSales.toFixed(2)}</TableCell>
              <TableCell>{report.generatedBy}</TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
      <div className="mt-4 font-bold">Total Store Sales: ETB {totalStoreSales.toFixed(2)}</div>
    </div>
  )
}

